### ISSUE TITLE
Xbox cursor appears when calling keyboard and never disappears again

### ISSUE THREAD

**Issue by daniel-dias** [Microsoft/TVHelpers#36] opened 2017-03-21 12:07 UTC
Hello,

I am developing an Javascript UWP app for Xbox.
Using the directional navigation works OK until i have an input and i call the Xbox keyboard.

After that, the Xbox cursor appears and i can't find a way to hide it.
This means that all the focus stop working, and i only can navigate my app with the cursor.

Is there any solution for that?

**Comment by payzer** [comment] 2017-03-21 14:08
I haven't seen this happen before. Is there any XAML involved by chance or is it a pure JS app?

Another thing to check is whether any code is changing this property: navigator.gamepadInputEmulation.

It should be "keyboard". You can check by going to the JavaScript console when the mouse cursor shows up & then typing "navigator.gamepadInputEmulation" into the console. It should be set to "keyboard"

**Comment by daniel-dias** [comment] 2017-03-21 14:34
Hi,

I have a XAML with only a Grid and a Webview, all the rest is JS.

About the property "navigator.gamepadInputEmulation", i've checked that it is always set as "keyboard" before and after the cursor appears.
I've also tried to set it again to "keyboard" but it has no effect.


I don't know if it is related, but on my App.xaml.cs, i have also this: Application.Current.RequiresPointerMode = ApplicationRequiresPointerMode.Auto;

I have seen on some posts that it should be set to: ApplicationRequiresPointerMode.WhenRequested, but when i do this both the cursor and the directional navigation stops working.

**Comment by payzer** [comment] 2017-03-21 14:39
Thank you that helps. In that case, I have heard of this happening before. Since there are two different UI frameworks involved, there are two ways of setting pointer mode.

If your app is only a Webview, have you considered a hosted web app or JavaScript UWP app? That would be simpler, smaller, faster & less memory. Or are you using XAML for something else?

In the other case where this happened, the developer switched to a pure HTML app to solve the problem, so unfortunately we never figured out the cause.

**Comment by payzer** [comment] 2017-05-18 17:44
This one's been open for a while so I'm going to go ahead and close it. If you still need assistance let us know.

**Closed by payzer** 2017-05-18 17:44 UTC
